# File: azure-pipelines.yml
name: $(Build.BuildId)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/$(Build.SourceBranchName)
    - repository: Infra
      type: git
      name: Libra - DevNet/Infra
      ref: main

trigger:
  - development
  - stylus

stages:
  - stage: Development
    variables:
      ReleaseNameLower: "librachain-nitro-tokenbridge"
      DockerFile: "**/tokenbridge/Dockerfile"
      BuildContext: "$(System.DefaultWorkingDirectory)/$(Build.Repository.Name)"
    jobs:
      - template: CICD/azure-pipeline.yml@Infra